### ISSUE TITLE
Parse out leading 1), 2), etc

### ISSUE THREAD

**Issue by coolaj86** [dashtesting/trello-github-etl#1]
The task issues could be much improved:

- Parse out leading 1), 2), etc
- Substr names to 50 characters (or so)
- place full issue name in body (if longer than 50 chars)

**Comment by riongull** [comment]
Started in https://github.com/dashtesting/trello-github-etl/commit/40a174a27dd799d6da59d873b2bd23903ad902cd and ended with https://github.com/dashtesting/trello-github-etl/commit/99f0f58d281c2af4c152bdbcd4213b503ec4efcf
