### ISSUE TITLE
Handle "Labels" for each Trello Card as labels or GH project column (Meta vs Paused, Completed)

### ISSUE THREAD

**Issue by riongull** [dashtesting/trello-github-etl#5]
Populate the GitHub-native "Labels" [project](https://github.com/orgs/dashtesting/projects/2/views/1) column for all [issues](https://github.com/dashtesting/migration1/issues):

Assumes existence of [`./board.json`](https://github.com/dashtesting/trello-github-etl/blob/main/etl.js#L16), which can be obtained from
- the [Trello board](https://trello.com/b/FPJzDcok/dash-incubator-app)
- "Show menu"
- "<" (if showing)
- "More..."
- "Print and export"

See the [Google Sheets Spec](https://docs.google.com/spreadsheets/d/16tC6h4iaw_Fdn_FiLxfAiNOEqRpe5azyqoTmJ7FnZiY/edit#gid=1220526302) for details.

**Comment by devPalacio** [comment]
I dug into the JSON file a little bit, the current accessor on the sheet points to the hash of the label. 
The actual text of the label is stored in cards[0].labels[0].name
Which way makes more sense? 
Do we want to capture the whole 'label' object with color and hash or just the text?

**Comment by riongull** [comment]
@devPalacio, thanks for taking this on. In all instances we want to return actual names instead of their Trello ids. Thanks for asking.

**Comment by devPalacio** [comment]
Complete list of labels:
Paused, Meta, Completed
